### ISSUE TITLE
Remove dependencies on aws-lambda

### ISSUE THREAD

**Issue by tettoffensive** [apuyou/apollo-server-nextjs#2]
I don't think you need this anymore: 
https://github.com/apuyou/apollo-server-nextjs/blob/0b2a73cc99c284c50ded320cd7c836be3b1e8e96/package.json#L32

**Comment by apuyou** [comment]
Hi, thanks for reporting this! That's right, I've just fixed it. I think it can wait for the next release as it doesn't depend on other packages, but if it's causing a problem for you, please tell me and I'll do a patch release :)
